# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 04:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. 10 digits allowed.", regex='^[7-9]\\d{9}$')])),
                ('email', models.CharField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Wrong email ')])),
                ('role', models.IntegerField(choices=[(0, 'Member'), (1, 'Admin')], default=0)),
            ],
        ),
    ]
